/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author Pablo_Fuentes
 */
public class FrmCliente extends javax.swing.JFrame {

    /**
     * Creates new form frm_01producto
     */
    public FrmCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jop_mensajes = new javax.swing.JOptionPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_idcliente = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        txt_usuario = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        txt_contrasenia = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        txt_nombre_cliente = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        txt_apellido_cliente = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        txt_precioucompra = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        txt_telefono_cliente = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_direccion_cliente = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_correoe_cliente = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        btn_salir = new javax.swing.JButton();
        btn_crear = new javax.swing.JButton();
        btn_actualizar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_reporte = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Administrador de Productos");
        setBackground(new java.awt.Color(187, 128, 201));
        setName("frm_01producto"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(1100, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("INGRESO DE PRODUCTO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 44, 40, -1));

        txt_idcliente.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txt_idcliente.setText("ID");
        txt_idcliente.setName("txt_idcliente"); // NOI18N
        getContentPane().add(txt_idcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 70, 40, -1));

        jSeparator1.setForeground(new java.awt.Color(204, 153, 255));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 10, 350));

        jSeparator2.setForeground(new java.awt.Color(204, 153, 255));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 29, -1, 65));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Usuario");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 44, 289, -1));

        txt_usuario.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txt_usuario.setText("Usuario");
        txt_usuario.setName("txt_usuario"); // NOI18N
        getContentPane().add(txt_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 69, 289, -1));

        jSeparator3.setForeground(new java.awt.Color(204, 153, 255));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 29, -1, 65));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Contraseña");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 41, 150, -1));

        txt_contrasenia.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txt_contrasenia.setText("Constraseña");
        txt_contrasenia.setName("txt_descripcion"); // NOI18N
        getContentPane().add(txt_contrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 66, 150, -1));

        jSeparator4.setForeground(new java.awt.Color(204, 153, 255));
        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(569, 29, 0, 62));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Nombre Cliente");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(578, 41, 150, -1));

        txt_nombre_cliente.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txt_nombre_cliente.setText("Nombre Cliente");
        txt_nombre_cliente.setName("txt_descripcion"); // NOI18N
        getContentPane().add(txt_nombre_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(578, 66, 150, -1));

        jSeparator5.setForeground(new java.awt.Color(204, 153, 255));
        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 100, 10, 60));

        jSeparator6.setForeground(new java.awt.Color(204, 153, 255));
        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 10, 50));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Apellido Cliente");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(749, 41, 150, -1));

        txt_apellido_cliente.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txt_apellido_cliente.setText("Apellido Cliente");
        txt_apellido_cliente.setName("txt_descripcion"); // NOI18N
        getContentPane().add(txt_apellido_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(749, 66, 162, -1));

        jSeparator7.setForeground(new java.awt.Color(204, 153, 255));
        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(916, 29, -1, 68));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Nit Cliente");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(925, 40, 134, -1));

        txt_precioucompra.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txt_precioucompra.setText("Nit Cliente");
        txt_precioucompra.setName("txt_descripcion"); // NOI18N
        getContentPane().add(txt_precioucompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(925, 65, 130, -1));

        jSeparator8.setForeground(new java.awt.Color(204, 153, 255));
        jSeparator8.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        getContentPane().add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 1010, 20));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Teléfono Cliente");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 170, -1));

        txt_telefono_cliente.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txt_telefono_cliente.setText("Telefono");
        txt_telefono_cliente.setName("txt_descripcion"); // NOI18N
        getContentPane().add(txt_telefono_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 170, -1));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Dirección Cliente");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 360, -1));

        txt_direccion_cliente.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txt_direccion_cliente.setText("Dirección");
        txt_direccion_cliente.setName("txt_descripcion"); // NOI18N
        getContentPane().add(txt_direccion_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 360, -1));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Correo Electrónico Cliente");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(642, 110, 420, -1));

        txt_correoe_cliente.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txt_correoe_cliente.setText("correo");
        txt_correoe_cliente.setName("txt_descripcion"); // NOI18N
        getContentPane().add(txt_correoe_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(642, 130, 420, -1));

        jSeparator12.setForeground(new java.awt.Color(204, 153, 255));
        jSeparator12.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 30, 10, 60));

        btn_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ic_java_4salir.png"))); // NOI18N
        btn_salir.setToolTipText("Regresar al menú principal");
        getContentPane().add(btn_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 40, 30));

        btn_crear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ic_java_1crear.png"))); // NOI18N
        btn_crear.setToolTipText("Crear (debe tener los campos llenos)");
        getContentPane().add(btn_crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 40, 30));

        btn_actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ic_java_2actulizar.png"))); // NOI18N
        btn_actualizar.setToolTipText("Actualizar (debe tener algún registro seleccionado)");
        getContentPane().add(btn_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 40, 30));

        btn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ic_java_3eliminar.png"))); // NOI18N
        btn_eliminar.setToolTipText("Eliminar (debe tener algún registro seleccionado)");
        getContentPane().add(btn_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 40, 30));

        btn_reporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ic_java_5reporte.png"))); // NOI18N
        btn_reporte.setToolTipText("Crear un reporte (Con los registros mostrados)");
        getContentPane().add(btn_reporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 40, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 990, 340));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondoLogin.png"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1070, 160));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondoLogin.png"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 156, 40, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_actualizar;
    public javax.swing.JButton btn_crear;
    public javax.swing.JButton btn_eliminar;
    public javax.swing.JButton btn_reporte;
    public javax.swing.JButton btn_salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTable jTable1;
    private javax.swing.JOptionPane jop_mensajes;
    public javax.swing.JTextField txt_apellido_cliente;
    public javax.swing.JTextField txt_contrasenia;
    public javax.swing.JTextField txt_correoe_cliente;
    public javax.swing.JTextField txt_direccion_cliente;
    public javax.swing.JTextField txt_idcliente;
    public javax.swing.JTextField txt_nombre_cliente;
    public javax.swing.JTextField txt_precioucompra;
    public javax.swing.JTextField txt_telefono_cliente;
    public javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables
}
